# Generated by Django 2.2.2 on 2019-06-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190611_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_notified',
            field=models.BooleanField(default=False),
        ),
    ]
