# Generated by Django 2.2.2 on 2019-06-13 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_event_is_notified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='facebook_id',
        ),
    ]
